import Head from 'next/head';
import Link from 'next/link';
import { Button, Card, Container } from 'react-bootstrap';
import useSWR from 'swr';

const AllPosts = () => {
  const { data: posts, error } = useSWR('/api/data/posts');
  return (
    <>
      <Head>
        <title>All Posts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <main className="py-5">
          <div className={`posts`}>
            {posts?.map((post) => {
              return (
                <div key={post?.id} className={`postcard`}>
                  <Card style={{ width: '18rem' }}>
                    <Card.Body>
                      <Card.Title>{post.title}</Card.Title>
                      <Card.Text>{post.body}</Card.Text>
                      <Button variant="primary">
                        <Link href={`/posts/${post.id}`}>Details</Link>
                      </Button>
                    </Card.Body>
                  </Card>
                </div>
              );
            })}
          </div>
        </main>
      </Container>
    </>
  );
};

// export const getServerSideProps = async (context) => {
//   const url = `https://jsonplaceholder.typicode.com/posts`;
//   const response = await axios.get(url);
//   const { data } = response;
//   return {
//     props: {
//       posts: data,
//     },
//   };
// };
export default AllPosts;
