import Head from 'next/head';
import Link from 'next/link';
import { Button, Container } from 'react-bootstrap';
import { SWRConfig } from 'swr';
import Posts from '../components/posts/Index';
import styles from '../styles/Home.module.css';

export default function Home(/*{ posts= {}}*/) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next Explore</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <SWRConfig value={{ provider: () => new Map() }}> */}
      <Container>
        <main className={styles.main}>
          <h1>Next Starter Template</h1>
          <Button>
            <Link href={`/posts`}>All Posts</Link>
          </Button>
          <SWRConfig>
            <Posts /*posts={posts}*/ />
          </SWRConfig>
        </main>
      </Container>
      {/* </SWRConfig> */}
    </div>
  );
}

// export const getServerSideProps = async (context) => {
//   const url = `https://jsonplaceholder.typicode.com/posts`;
//   const response = await axios.get(url);
//   const { data } = response;
//   return {
//     props: {
//       posts: data.slice(0, 10),
//     },
//   };
// };
